{"trial_id": "0000", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 3, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_0", "default": null, "conditions": [], "min_value": 16, "max_value": 128, "step": 32, "sampling": "linear"}}, {"class_name": "Boolean", "config": {"name": "use_batchnorm_0", "default": false, "conditions": []}}, {"class_name": "Boolean", "config": {"name": "use_dropout_0", "default": false, "conditions": []}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.0001], "ordered": true}}, {"class_name": "Float", "config": {"name": "dropout_rate0", "default": 0.2, "conditions": [], "min_value": 0.2, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 16, "max_value": 128, "step": 32, "sampling": "linear"}}, {"class_name": "Boolean", "config": {"name": "use_batchnorm_1", "default": false, "conditions": []}}, {"class_name": "Boolean", "config": {"name": "use_dropout_1", "default": false, "conditions": []}}], "values": {"num_layers": 2, "units_0": 80, "use_batchnorm_0": true, "use_dropout_0": true, "learning_rate": 0.0001, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 3, "tuner/round": 0, "dropout_rate0": 0.2, "units_1": 16, "use_batchnorm_1": false, "use_dropout_1": false}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\user\\anaconda3\\envs\\tf-env\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\user\\anaconda3\\envs\\tf-env\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\user\\anaconda3\\envs\\tf-env\\lib\\site-packages\\keras_tuner\\src\\tuners\\hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\user\\anaconda3\\envs\\tf-env\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"C:\\Users\\user\\anaconda3\\envs\\tf-env\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"C:\\Users\\user\\anaconda3\\envs\\tf-env\\lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"C:\\Users\\user\\anaconda3\\envs\\tf-env\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\user\\AppData\\Local\\Temp\\ipykernel_16348\\2640817343.py\", line 8, in huber_fn\n    return tf.where(is_small_error, squared_loss, linear_loss)\nNameError: name 'squared_loss' is not defined. Did you mean: 'sqaured_loss'?\n"}